# Default values for DotNetCoreDocker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

containerPort: 5000
containerPortHttps: 5001

certificatePassword: "createyourownpassword"

image:
  repository: anderslybecker/k8sfriendlyaspnetcore
  tag: v1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer #ClusterIP
  port: 443