apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  certificatePassword: {{ .Values.certificatePassword | b64enc }}
  certificate: {{ include ( print $.Template.BasePath "/_aspnetcore-cert.pfx") . | b64enc }}