trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  imgTage: '$(Build.BuildId)'
  projects: '**/*.csproj'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(projects)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: $(projects)
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(projects)
    arguments: '--configuration $(BuildConfiguration) --no-build --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  displayName: 'Docker build & push'
  inputs:
    containerRegistry: 'Lybecker Docker Hub'
    repository: 'anderslybecker/k8sfriendlyaspnetcore'
    command: 'buildAndPush'
    Dockerfile: 'SimpleDockerfile'
    buildContext: '$(build.artifactstagingdirectory)/src/'
    tags: |
      $(imgTage)