trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'
  projects: 'src/*.csproj'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(projects)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: $(projects)
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(projects)
    arguments: '--configuration $(BuildConfiguration) --no-restore --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'Lybecker Docker Hub'
    repository: 'anderslybecker/k8sfriendlyaspnetcore'
    command: 'buildAndPush'
    Dockerfile: '**/SimpleDockerfile'
    buildContext: '$(build.artifactstagingdirectory)'
    tags: |
      $(imageTag)