# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # Container registry service connection established during pipeline creation
  # dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
  # imageRepository: '{{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}'
  # containerRegistry: '{{ containerRegistryConnection.Authorization.Parameters.loginServer }}'
  tag: '$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: dotnet restore "./k8s-friendly-aspnetcore.csproj"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: dotnet publish "k8s-friendly-aspnetcore.csproj" -c Release -o /app

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: docker build -t anderslybecker/fisk:$(tag) .