apiVersion: v1
kind: Service
metadata:
  name: {{ include "DotNetCoreDocker.fullname" . }}
  labels:
{{ include "DotNetCoreDocker.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.containerPortHttps }}
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "DotNetCoreDocker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
