name: CI
on: [push, pull_request]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: dotnet restore
        run: dotnet restore src/
      - name: dotnet build
        run: dotnet build src/ --configuration Release /p:Version=$GITHUB_SHA --no-restore
      - name: dotnet test
        run: dotnet test src/ --configuration Release --no-build
      - name: dotnet publish
        run: dotnet publish src/ --configuration Release --no-build --output /out
